main: org.ranin.TrueDestiny.App
name: "TrueDestiny"
version: 0.1.0
api-version: 1.16
authors: ["chibbi", "raninninn"]
description: "An exhaustive plugin to make roleplay servers even more enjoyable and challengin."
website: "www.spigotmc.org"
commands:
   warn:
      description: "warns a player"
      permission: warn
   hobby:
      description: "lets you choose your hobby"
      permission: hobby
   job:
      description: "lets you choose your job"
      aliases: ["jb"]
      permission: job
   race:
      description: "warns a player"
      permission: race
permissions:
   warn:
      description: Permission for the /warn command
      default: op
   hobby:
      description: Permission for the /hobby command
      default: true
   job:
      description: Permission for the /job command
      default: true
   race:
      description: Permission for the /race command
      default: true